name: Publish MKDocs 
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    if: github.repository == 'GOES/hol-005-agentic-studio'
    runs-on: goes-runners
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure pip is installed
        run: |
          sudo apt update
          sudo apt-get install -y python3-pip

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Version checks
        run: |
          python3 --version
          pip3 --version

      - name: Install Python packages
        run: sudo pip3 install -r requirements.txt
        working-directory: instructor/mkdocs/

      - name: Deploy MKDocs to GH Pages
        run: | 
          mkdocs gh-deploy --force
        working-directory: instructor/mkdocs/